# Generated by Django 3.2.10 on 2022-02-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('network_id', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('network_id', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('friends', models.ManyToManyField(to='network_api.Friend')),
                ('relations', models.ManyToManyField(to='network_api.Relation')),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='relations',
            field=models.ManyToManyField(to='network_api.Relation'),
        ),
    ]
