# Generated by Django 3.2.10 on 2022-02-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='network_id',
            field=models.CharField(default='default', max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
