# Generated by Django 3.2.10 on 2022-02-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_api', '0003_auto_20220207_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='network_id',
            field=models.CharField(default='default value', max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='relations',
            field=models.ManyToManyField(to='network_api.Relation'),
        ),
        migrations.AddField(
            model_name='person',
            name='relations',
            field=models.ManyToManyField(to='network_api.Relation'),
        ),
    ]
